## **In last module, we learnt a little about the very useful library Pandas widely used for Data Analysis. It is time to put the many utilities of this library in front of our eyes. We will be performing following manipulations and exploration of our data:**

* ### Indexing and slicing operations
* ### Manipulating columns
* ### Exploring unique and missing values

In [113]:
# Import pandas package
import pandas as pd
import numpy as np

## Let us read our data first

In [247]:
# loading csv File
file_path = 'movie_dataset.csv'
df=pd.read_csv(file_path)
df2=pd.read_csv(file_path)

In [115]:
df.shape

(2888, 20)

In [116]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino

In [117]:
df.tail(10)

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
2878,2878,20000000,Comedy,NaN,10073,date diary parents-in-law bridegroom wedding,en,Spoof of romantic comedies which focuses on a ...,10.098722,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",38765,48548426,83,An Unprotected Comedy,Date Movie,3.6,222,Alyson Hannigan Adam Campbell Sophie Monk Jenn...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",Jason Friedberg
2879,2879,23000000,Adventure Thriller,NaN,580,shark attack bahamas dying and death aggressio...,en,"After another deadly shark attack, Ellen Brody...",12.777008,"[{""name"": ""Universal Pictures"", ""id"": 33}]",31975,51881013,89,"This time, it’s personal.",Jaws: The Revenge,3.5,224,Lorraine Gary Lance Guest Mario Van Peebles Mi...,"[{'name': 'John M. Dwyer', 'gender': 2, 'depar...",Joseph Sargent
2880,2880,54000000,Drama,http://www.sonypictures.com/homevideo/catalog/...,8046,new york mentally disabled kidnapping blackmai...,en,Gigli is ordered to kidnap the psychologically...,9.053456,"[{""name"": ""City Light Films"", ""id"": 136}, {""na...",37834,7266209,121,Life doesn't play by the rules.,Gigli,3.5,104,Ben Affleck Jennifer Lopez Justin Bartha Laini...,"[{'name': 'Gary Frutkoff', 'gender': 2, 'depar...",Martin Brest
2881,2881,25000000,Action Adventure Fantasy Horror,http://www.bloodrayne-themovie.com/main/index....,168705,vampire vampire hunter based on video game rom...,en,"In eighteenth century Romania, Rayne, a dhampi...",7.008216,"[{""name"": ""Boll KG"", ""id"": 15127}]",38647,2405420,95,Revenge never tasted so sweet.,BloodRayne,3.5,118,Kristanna Loken Ben Kingsley Michelle Rodrigue...,"[{'name': 'Guinevere Turner', 'gender': 1, 'de...",Uwe Boll
2882,2882,40000000,Horror Thriller,NaN,9544,race against time psychopath homepage cop doctor,en,"With four corpses on his hands, New York City ...",6.756886,"[{""name"": ""Milagro Films"", ""id"": 1070}, {""name...",37477,18902015,101,The last site you'll ever see.,FearDotCom,3.2,105,Stephen Dorff Natascha McElhone Stephen Rea Ud...,"[{'name': 'Christian Sebaldt', 'gender': 2, 'd...",William Malone
2883,2883,20000000,Action Adventure Comedy,NaN,9760,NaN,en,"When Edward, Peter, Lucy and Susan each follow...",6.064638,"[{""name"": ""Twentieth Century Fox Film Corporat...",39107,86865564,86,We know it's big. We measured.,Epic Movie,3.2,326,Kal Penn Adam Campbell Jennifer Coolidge Jayma...,"[{'name': 'William A. Elliott', 'gender': 0, '...",Jason Friedberg
2884,2884,20000000,Action Fantasy Horror Thriller,NaN,12142,detective monster professor island museum,en,Edward Carnby is a private investigator specia...,9.292987,"[{""name"": ""Boll Kino Beteiligungs GmbH & Co. K...",38380,10442808,96,Can mankind defeat the army of darkness unleas...,Alone in the Dark,3.1,173,Christian Slater Tara Reid Stephen Dorff Frank...,"[{'name': 'Uwe Boll', 'gender': 2, 'department...",Uwe Boll
2885,2885,25000000,Action Comedy,http://www.disastermovie.net/,13805,natural disaster violence mortal danger during...,en,"In DISASTER MOVIE, the filmmaking team behind ...",16.238961,"[{""name"": ""Grosvenor Park Media Ltd."", ""id"": 2...",39689,14109284,87,Your favorite movies are going to be destroyed.,Disaster Movie,3.0,240,Matt Lanter Vanessa Lachey Nicole Ari Parker C...,"[{'name': 'Peck Prior', 'gender': 2, 'departme...",Jason Friedberg
2886,2886,44000000,Action Science Fiction War,NaN,5491,based on novel post-apocalyptic dystopia minin...,en,"In the year 3000, man is no match for the Psyc...",7.891470,"[{""name"": ""Franchise Pictures"", ""id"": 1403}, {...",36656,21400000,118,Take Back The Planet,Battlefield Earth,3.0,255,John Travolta Barry Pepper Forest Whitaker Kim...,"[{'name': 'Lynn Stalmaster', 'gender': 2, 'dep...",Roger Christian
2887,2887,100000000,Action Adventure Fantasy Science Fiction Thriller,NaN,14164,karate superhero revenge dragon duringcreditss...,en,The young warrior Son Goku sets out on a quest...,21.677732,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",39904,0,85,The legend comes to life.,Dragonball Evolution,2.9,462,Chow Yun-fat Justin Chatwin Joon Park Jamie Ch...,"[{'name': 'James Wong', 'gender': 2, 'departme...",James Wong

In [118]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2888 entries, 0 to 2887
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 2888 non-null   int64
 1   budget                2888 non-null   int64
 2   genres                2888 non-null   str
 3   homepage              1259 non-null   str
 4   id                    2888 non-null   int64
 5   keywords              2845 non-null   str
 6   original_language     2888 non-null   str
 7   overview              2888 non-null   str
 8   popularity            2888 non-null   float64
 9   production_companies  2888 non-null   str
 10  release_date          2888 non-null   int64
 11  revenue               2888 non-null   int64
 12  runtime               2888 non-null   int64
 13  tagline               2730 non-null   str
 14  title                 2888 non-null   str
 15  vote_average          2888 non-null   float64
 16  vote_count            2888 non-null   int64
 17  cast                  2888 non-null   str
 18  crew                  2888 non-null   str
 19  director              2888 non-null   str
dtypes: float64(2), int64(7), str(11)
memory usage: 451.4 KB

# <u>**<code>describe()</code>**</u>

## This method gives the overall descriptive summary of the dataframe. This works only for numerical columns

In [119]:
df.describe(include='all')

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
count,2888.000000,2.888000e+03,2888,1259,2888.000000,2845,2888,2888,2888.000000,2888,2888.000000,2.888000e+03,2888.000000,2730,2888,2888.000000,2888.000000,2888,2888,2888
unique,NaN,NaN,876,1239,NaN,2828,24,2888,NaN,2413,NaN,NaN,NaN,2722,2886,NaN,NaN,2871,2888,1234
top,NaN,NaN,Comedy,http://www.thehungergames.movie/,NaN,duringcreditsstinger,en,Framed in the 1940s for the double murder of h...,NaN,"[{""name"": ""Paramount Pictures"", ""id"": 4}]",NaN,NaN,NaN,There are no clean getaways.,Batman,NaN,NaN,William Shatner Leonard Nimoy DeForest Kelley ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Steven Spielberg
freq,NaN,NaN,169,4,NaN,8,2779,1,NaN,39,NaN,NaN,NaN,2,2,NaN,NaN,6,1,27
mean,1443.500000,4.455166e+07,NaN,NaN,46557.648546,NaN,NaN,NaN,32.521757,NaN,37780.700831,1.330831e+08,110.845914,NaN,NaN,6.358726,1100.020429,NaN,NaN,NaN
std,833.838114,4.543170e+07,NaN,NaN,78311.132756,NaN,NaN,NaN,36.852001,NaN,4234.819093,1.934428e+08,20.045847,NaN,NaN,0.837566,1449.607453,NaN,NaN,NaN
min,0.000000,1.600000e+05,NaN,NaN,5.000000,NaN,NaN,NaN,1.551497,NaN,9872.000000,0.000000e+00,63.000000,NaN,NaN,2.900000,100.000000,NaN,NaN,NaN
25%,721.750000,1.400000e+07,NaN,NaN,3599.250000,NaN,NaN,NaN,14.294301,NaN,36353.750000,2.181884e+07,97.000000,NaN,NaN,5.800000,271.000000,NaN,NaN,NaN
50%,1443.500000,3.000000e+07,NaN,NaN,10675.000000,NaN,NaN,NaN,23.439766,NaN,38758.000000,6.816994e+07,107.000000,NaN,NaN,6.400000,562.500000,NaN,NaN,NaN
75%,2165.250000,6.000000e+07,NaN,NaN,49014.000000,NaN,NaN,NaN,40.218528,NaN,40662.000000,1.601493e+08,121.000000,NaN,NaN,7.000000,1279.250000,NaN,NaN,NaN
max,2887.000000,3.800000e+08,NaN,NaN,417859.000000,NaN,NaN,NaN,875.581305,NaN,42629.000000,2.787965e+09,248.000000,NaN,NaN,8.500000,13752.000000,NaN,NaN,NaN

# <u>**Indexing and Slicing**</u>

In [120]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino

## **<code>iloc</code>** gets rows (or columns) at particular positions in the index (so it only takes integers).

In [121]:
# Let us get a subset which consists of first 8 rows and first 4 columns
df.iloc[:,-3:]

,cast,crew,director
0,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont
1,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
2,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle
3,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
4,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino
...,...,...,...
2883,Kal Penn Adam Campbell Jennifer Coolidge Jayma...,"[{'name': 'William A. Elliott', 'gender': 0, '...",Jason Friedberg
2884,Christian Slater Tara Reid Stephen Dorff Frank...,"[{'name': 'Uwe Boll', 'gender': 2, 'department...",Uwe Boll
2885,Matt Lanter Vanessa Lachey Nicole Ari Parker C...,"[{'name': 'Peck Prior', 'gender': 2, 'departme...",Jason Friedberg
2886,John Travolta Barry Pepper Forest Whitaker Kim...,"[{'name': 'Lynn Stalmaster', 'gender': 2, 'dep...",Roger Christian
2887,Chow Yun-fat Justin Chatwin Joon Park Jamie Ch...,"[{'name': 'James Wong', 'gender': 2, 'departme...",James Wong

## **<code>loc</code>** gets rows (or columns) with particular labels from the index.

In [ ]:
# Now let us subset our dataframe in which we want to have first 8 rows identified with their rows labels and some named columns
df.loc[0:8,['title','budget','revenue']]
# df.loc[50:60,['title','budget','revenue']]

                      title     budget     revenue
0  The Shawshank Redemption   25000000    28341469
1             The Godfather    6000000   245066411
2                  Whiplash    3300000    13092000
3                Fight Club   63000000   100853753
4              Pulp Fiction    8000000   213928762
5             Spirited Away   15000000   274925095
6    The Godfather: Part II   13000000    47542841
7          Schindler's List   22000000   321365567
8           The Dark Knight  185000000  1004558444

In [124]:
df.loc[:,['title','budget','revenue']]

                         title     budget    revenue
0     The Shawshank Redemption   25000000   28341469
1                The Godfather    6000000  245066411
2                     Whiplash    3300000   13092000
3                   Fight Club   63000000  100853753
4                 Pulp Fiction    8000000  213928762
...                        ...        ...        ...
2883                Epic Movie   20000000   86865564
2884         Alone in the Dark   20000000   10442808
2885            Disaster Movie   25000000   14109284
2886         Battlefield Earth   44000000   21400000
2887      Dragonball Evolution  100000000          0

[2888 rows x 3 columns]

In [125]:
df[0:10]

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino
5,5,15000000,Fantasy Adventure Animation Family,http://movies.disney.com/spirited-away,129,witch parents kids relationship magic twilight...,ja,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]",37092,274925095,125,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840,Rumi Hiiragi Miyu Irino Mari Natsuki Takashi N...,"[{'name': 'John Lasseter', 'gender': 2, 'depar...",Hayao Miyazaki
6,6,13000000,Drama Crime,NaN,240,italo-american cuba vororte melancholy praise,en,In the continuing saga of the Corleone crime f...,105.792936,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",27383,47542841,200,"I don't feel I have to wipe everybody out, Tom...",The Godfather: Part II,8.3,3338,Al Pacino Robert Duvall Diane Keaton Robert De...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
7,7,22000000,Drama History War,http://www.schindlerslist.com/,424,factory concentration camp hero holocaust worl...,en,The true story of how businessman Oskar Schind...,104.469351,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",34302,321365567,195,"Whoever saves one life, saves the world entire.",Schindler's List,8.3,4329,Liam Neeson Ben Kingsley Ralph Fiennes Carolin...,"[{'name': 'John Williams', 'gender': 2, 'depar...",Steven Spielberg
8,8,185000000,Drama Action Crime Thriller,http://thedarkknight.warnerbros.com/dvdsite/,155,dc comics crime fighter secret identity scarec...,en,Batman raises the stakes in his war on crime. ...,187.322927,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...",39645,1004558444,152,Why So Serious?,The Dark Knight,8.2,12002,Christian Bale Heath Ledger Aaron Eckhart Mich...,"[{'name': 'Lucinda Syson', 'gender': 1, 'depar...",Christopher Nolan
9,9,55000000,Comedy Drama Romance,NaN,13,vietnam veteran hippie mentally disabled runni...,en,A man with a low IQ has accomplished great thi...,138.133331,"[{""name"": ""Paramount Pictures"", ""id"": 4}]",34521,677945399,142,"The world will never be the same, once you've ...",Forrest Gump,8.2,7927,Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,"[{'name': 'Alan Silvestri', 'gender': 2, 'depa...",Robert Zemeckis

In [126]:
df[['title','director','genres']]

,title,director,genres
0,The Shawshank Redemption,Frank Darabont,Drama Crime
1,The Godfather,Francis Ford Coppola,Drama Crime
2,Whiplash,Damien Chazelle,Drama
3,Fight Club,David Fincher,Drama
4,Pulp Fiction,Quentin Tarantino,Thriller Crime
...,...,...,...
2883,Epic Movie,Jason Friedberg,Action Adventure Comedy
2884,Alone in the Dark,Uwe Boll,Action Fantasy Horror Thriller
2885,Disaster Movie,Jason Friedberg,Action Comedy
2886,Battlefield Earth,Roger Christian,Action Science Fiction War
2887,Dragonball Evolution,James Wong,Action Adventure Fantasy Science Fiction Thriller

In [127]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'overview', 'popularity', 'production_companies',
       'release_date', 'revenue', 'runtime', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='str')

## <b>In fact we can also perform boolean indexing on our dataframe</b>

In [128]:
df['original_language'] == 'en'

0       True
1       True
2       True
3       True
4       True
        ...
2883    True
2884    True
2885    True
2886    True
2887    True
Name: original_language, Length: 2888, dtype: bool

In [129]:
# Boolean Indexing
english_movies = df[df['original_language'] == 'en']
english_movies.head()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino

In [130]:
english_movies.shape

(2779, 20)

In [131]:
non_english_movies = df[df['vote_average'] != 9.0]
non_english_movies.head()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino

In [132]:
long_movies = df[df['runtime'] > 120]
long_movies[['title','director','runtime']]

,title,director,runtime
0,The Shawshank Redemption,Frank Darabont,142
1,The Godfather,Francis Ford Coppola,175
3,Fight Club,David Fincher,139
4,Pulp Fiction,Quentin Tarantino,154
5,Spirited Away,Hayao Miyazaki,125
...,...,...,...
2766,How Do You Know,James L. Brooks,121
2855,Batman & Robin,Joel Schumacher,125
2863,Speed 2: Cruise Control,Jan de Bont,121
2869,In the Name of the King: A Dungeon Siege Tale,Uwe Boll,127
2880,Gigli,Martin Brest,121

## Infact we can match conditions for mutliple columns

In [134]:
long_movies = df[df['vote_average']  > 7.3]
long_movies[['title','director','vote_average']]

                        title               director  vote_average
0    The Shawshank Redemption         Frank Darabont           8.5
1               The Godfather   Francis Ford Coppola           8.4
2                    Whiplash        Damien Chazelle           8.3
3                  Fight Club          David Fincher           8.3
4                Pulp Fiction      Quentin Tarantino           8.3
..                        ...                    ...           ...
334           This Is England          Shane Meadows           7.4
335               The Verdict           Sidney Lumet           7.4
336   The Secret Life of Bees  Gina Prince-Bythewood           7.4
337       Fiddler on the Roof         Norman Jewison           7.4
338          The Lost Weekend           Billy Wilder           7.4

[339 rows x 3 columns]

In [135]:
long_movies.tail()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
334,334,2380000,Drama Crime,http://www.thisisenglandmovie.co.uk/,11798,holiday skinhead england vandalism independent...,en,A story about a troubled boy growing up in Eng...,8.395624,"[{""name"": ""EM Media"", ""id"": 1917}, {""name"": ""U...",38972,8176544,101,"Run with the crowd, stand alone, you decide.",This Is England,7.4,363,Thomas Turgoose Stephen Graham Jo Hartley Andr...,"[{'name': 'Tessa Ross', 'gender': 1, 'departme...",Shane Meadows
335,335,16000000,Drama,NaN,24226,boston court malpractice alcoholic courtroom,en,"Frank Galvin is a down-on-his luck lawyer, red...",7.980632,"[{""name"": ""Twentieth Century Fox Film Corporat...",30293,53977250,129,"The doctors want to settle, the Church wants t...",The Verdict,7.4,131,Paul Newman Charlotte Rampling Jack Warden Jam...,"[{'name': 'Peter C. Frank', 'gender': 2, 'depa...",Sidney Lumet
336,336,11000000,Adventure,http://www.foxsearchlight.com/thesecretlifeofb...,12837,woman director,en,"Set in South Carolina in 1964, this is the tal...",7.645979,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43...",39708,38105395,114,"Bring Your Girlfriends, Sisters, Mothers and D...",The Secret Life of Bees,7.4,158,Dakota Fanning Queen Latifah Jennifer Hudson S...,"[{'name': 'Will Smith', 'gender': 2, 'departme...",Gina Prince-Bythewood
337,337,9000000,Drama Romance,NaN,14811,tradition dream musical pogrom mother daughter...,en,This lavishly produced and critically acclaime...,7.623979,"[{""name"": ""United Artists"", ""id"": 60}, {""name""...",26240,83304330,181,To Life!,Fiddler on the Roof,7.4,134,Chaim Topol Norma Crane Leonard Frey Molly Pic...,"[{'name': 'John Williams', 'gender': 2, 'depar...",Norman Jewison
338,338,1250000,Drama,NaN,28580,desperation weekend delirium addiction alcoholism,en,"Don Birnam, a long-time alcoholic, has been so...",6.903314,"[{""name"": ""Paramount"", ""id"": 6033}]",16766,11000000,101,The screen dares to open the strange and savag...,The Lost Weekend,7.4,112,Ray Milland Jane Wyman Phillip Terry Howard Da...,"[{'name': 'Billy Wilder', 'gender': 0, 'depart...",Billy Wilder

In [136]:
(df['vote_average']  > 7.3) & (df['runtime'] > 120)

0        True
1        True
2       False
3        True
4        True
        ...
2883    False
2884    False
2885    False
2886    False
2887    False
Length: 2888, dtype: bool

In [137]:
long_english_movies = df[(df['vote_average']  > 7.3) & (df['runtime'] > 120)]
long_english_movies.head()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino
5,5,15000000,Fantasy Adventure Animation Family,http://movies.disney.com/spirited-away,129,witch parents kids relationship magic twilight...,ja,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]",37092,274925095,125,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840,Rumi Hiiragi Miyu Irino Mari Natsuki Takashi N...,"[{'name': 'John Lasseter', 'gender': 2, 'depar...",Hayao Miyazaki

In [138]:
long_english_movies.shape

(186, 20)

# <u>**Next let us see how we can manipulate columns**</u>

In [139]:
df.shape

(2888, 20)

## **Let's say if you wanted a new column whose values were half the movie runtime**

In [140]:
df['runtime']

0       142
1       175
2       105
3       139
4       154
       ...
2883     86
2884     96
2885     87
2886    118
2887     85
Name: runtime, Length: 2888, dtype: int64

In [142]:
# Add new column which is just half the runtime
df['half_runtime'] = df['runtime'] * 0.5

In [143]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,...,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director,half_runtime
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",...,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont,71.0
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola,87.5
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",...,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle,52.5
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",...,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher,69.5
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",...,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino,77.0

## We can also create a new column by adding two existing columns

In [144]:
# Creating another new column by subtracting/adding two existing columns
df['movie_profit'] = df['revenue'] - df['budget']

In [145]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,...,runtime,tagline,title,vote_average,vote_count,cast,crew,director,half_runtime,movie_profit
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",...,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont,71.0,3341469
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola,87.5,239066411
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",...,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle,52.5,9792000
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",...,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher,69.5,37853753
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",...,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino,77.0,205928762

## **Next, we can also drop some columns which we want to drop**

In [146]:
# Remove column
df.drop(['id'], axis = 1, inplace=True)

In [147]:
df.head()

,index,budget,genres,homepage,keywords,original_language,overview,popularity,production_companies,release_date,...,runtime,tagline,title,vote_average,vote_count,cast,crew,director,half_runtime,movie_profit
0,0,25000000,Drama Crime,NaN,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,...,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont,71.0,3341469
1,1,6000000,Drama Crime,http://www.thegodfather.com/,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,...,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola,87.5,239066411
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,...,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle,52.5,9792000
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,...,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher,69.5,37853753
4,4,8000000,Thriller Crime,NaN,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,...,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino,77.0,205928762

In [148]:
df.describe()

,index,budget,popularity,release_date,revenue,runtime,vote_average,vote_count,half_runtime,movie_profit
count,2888.000000,2.888000e+03,2888.000000,2888.000000,2.888000e+03,2888.000000,2888.000000,2888.000000,2888.000000,2.888000e+03
mean,1443.500000,4.455166e+07,32.521757,37780.700831,1.330831e+08,110.845914,6.358726,1100.020429,55.422957,8.853143e+07
std,833.838114,4.543170e+07,36.852001,4234.819093,1.934428e+08,20.045847,0.837566,1449.607453,10.022923,1.654285e+08
min,0.000000,1.600000e+05,1.551497,9872.000000,0.000000e+00,63.000000,2.900000,100.000000,31.500000,-1.657101e+08
25%,721.750000,1.400000e+07,14.294301,36353.750000,2.181884e+07,97.000000,5.800000,271.000000,48.500000,8.652608e+05
50%,1443.500000,3.000000e+07,23.439766,38758.000000,6.816994e+07,107.000000,6.400000,562.500000,53.500000,3.449484e+07
75%,2165.250000,6.000000e+07,40.218528,40662.000000,1.601493e+08,121.000000,7.000000,1279.250000,60.500000,1.097184e+08
max,2887.000000,3.800000e+08,875.581305,42629.000000,2.787965e+09,248.000000,8.500000,13752.000000,124.000000,2.550965e+09

## You can drop  multiple columns at once too.

In [150]:
df.drop(['half_runtime','homepage'],axis=1,inplace=True)

In [151]:
df.drop(['crew'], axis = 1, inplace=True)

In [152]:
df.head()

,index,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit
0,0,25000000,Drama Crime,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,Frank Darabont,3341469
1,1,6000000,Drama Crime,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,Francis Ford Coppola,239066411
2,2,3300000,Drama,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,Damien Chazelle,9792000
3,3,63000000,Drama,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,David Fincher,37853753
4,4,8000000,Thriller Crime,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,Quentin Tarantino,205928762

## **We can do a lot of basic operations as well**

In [153]:
# Find the sum of values in a column
df['budget'].sum()

np.int64(128665192296)

In [154]:
# What if there is a null value
df.loc[:1,'revenue'] = np.nan

In [155]:
df.iloc[:5]

,index,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit
0,0,25000000,Drama Crime,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,NaN,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,Frank Darabont,3341469
1,1,6000000,Drama Crime,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,NaN,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,Francis Ford Coppola,239066411
2,2,3300000,Drama,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000.0,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,Damien Chazelle,9792000
3,3,63000000,Drama,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753.0,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,David Fincher,37853753
4,4,8000000,Thriller Crime,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762.0,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,Quentin Tarantino,205928762

In [157]:
df.set_index('index', inplace=True)

In [175]:
df.head()

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit,Capitalized_title
index,,,,,,,,,,,,,,,,,,
0,25000000,Drama Crime,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,NaN,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,Frank Darabont,3341469,THE SHAWSHANK REDEMPTION
1,6000000,Drama Crime,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,NaN,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,Francis Ford Coppola,239066411,THE GODFATHER
2,3300000,Drama,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000.0,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,Damien Chazelle,9792000,WHIPLASH
3,63000000,Drama,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753.0,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,David Fincher,37853753,FIGHT CLUB
4,8000000,Thriller Crime,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762.0,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,Quentin Tarantino,205928762,PULP FICTION

In [174]:
df.iloc[:3]

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit,Capitalized_title
index,,,,,,,,,,,,,,,,,,
0,25000000,Drama Crime,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,NaN,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,Frank Darabont,3341469,THE SHAWSHANK REDEMPTION
1,6000000,Drama Crime,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,NaN,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,Francis Ford Coppola,239066411,THE GODFATHER
2,3300000,Drama,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000.0,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,Damien Chazelle,9792000,WHIPLASH

In [179]:
df.loc[[2344,2798]]

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit,Capitalized_title
index,,,,,,,,,,,,,,,,,,
2344,100000000,Thriller Science Fiction Action Adventure,gorilla space marine space suit revolution chimp,en,After a spectacular crash-landing on an unchar...,51.188633,"[{""name"": ""Twentieth Century Fox Film Corporat...",37097,362211740.0,119,You'll be sorry you were ever born human,Planet of the Apes,5.6,1243,Mark Wahlberg Tim Roth Helena Bonham Carter Mi...,Tim Burton,262211740,PLANET OF THE APES
2798,20000000,Horror Mystery Thriller,candy loss of sister mobile phone answering ma...,en,Several people start receiving voice-mails fro...,12.458131,"[{""name"": ""Intermedia Films"", ""id"": 763}, {""na...",39451,0.0,87,What will it sound like when you die?,One Missed Call,4.7,171,Shannyn Sossamon Edward Burns Ana Claudia Tala...,Eric Valette,-20000000,ONE MISSED CALL

In [163]:
df.head()

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit
index,,,,,,,,,,,,,,,,,
0,25000000,Drama Crime,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,NaN,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,Frank Darabont,3341469
1,6000000,Drama Crime,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,NaN,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,Francis Ford Coppola,239066411
2,3300000,Drama,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000.0,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,Damien Chazelle,9792000
3,63000000,Drama,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753.0,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,David Fincher,37853753
4,8000000,Thriller Crime,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762.0,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,Quentin Tarantino,205928762

In [164]:
df['runtime'].sum()

np.int64(320123)

In [165]:
print(f" The shortest movie length is {df['runtime'].min()}")
print(f" The largest movie length is {df['runtime'].max()}")

 The shortest movie length is 63
 The largest movie length is 248

In [166]:
df[df['runtime']== 0.0]

Empty DataFrame
Columns: [budget, genres, keywords, original_language, overview, popularity, production_companies, release_date, revenue, runtime, tagline, title, vote_average, vote_count, cast, director, movie_profit]
Index: []

# **<code>apply()</code>** method applies a function to every row in a pandas dataframe

In [170]:
# Suppose we want to convert the column network to uppercase

def to_uppercase(column):
  return column.upper()

to_uppercase("python")

'PYTHON'

In [171]:
df['Capitalized_title'] = df['title'].apply(to_uppercase)

In [172]:
df.head()

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit,Capitalized_title
index,,,,,,,,,,,,,,,,,,
0,25000000,Drama Crime,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,NaN,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,Frank Darabont,3341469,THE SHAWSHANK REDEMPTION
1,6000000,Drama Crime,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,NaN,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,Francis Ford Coppola,239066411,THE GODFATHER
2,3300000,Drama,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000.0,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,Damien Chazelle,9792000,WHIPLASH
3,63000000,Drama,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753.0,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,David Fincher,37853753,FIGHT CLUB
4,8000000,Thriller Crime,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762.0,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,Quentin Tarantino,205928762,PULP FICTION

## Another way to use <code>apply()</code> involves the use of <code>lambda()</code> function.

* ### A <code>lambda()</code> function is a small anonymous function.
* ### A <code>lambda()</code> function can take any number of arguments, but can only have one expression.

In [182]:
def add_two_numbers(a,b):
  return a+b

In [181]:
x = lambda a,b : a+b
x(1,5)

6

In [187]:
# lambda function - Row wise operation
def revised_profit(revenue, budget):
  if revenue > 0:
    new_profit = revenue - budget
  else:
    new_profit = np.nan

  return new_profit

In [188]:
df['new_profit'] = df.apply(lambda x: revised_profit(x['revenue'], x['budget']),axis=1)

In [186]:
df.head()

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit,Capitalized_title,new_profit
index,,,,,,,,,,,,,,,,,,,
0,25000000,Drama Crime,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,NaN,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,Frank Darabont,3341469,THE SHAWSHANK REDEMPTION,NaN
1,6000000,Drama Crime,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,NaN,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,Francis Ford Coppola,239066411,THE GODFATHER,NaN
2,3300000,Drama,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000.0,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,Damien Chazelle,9792000,WHIPLASH,9792000.0
3,63000000,Drama,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753.0,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,David Fincher,37853753,FIGHT CLUB,37853753.0
4,8000000,Thriller Crime,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762.0,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,Quentin Tarantino,205928762,PULP FICTION,205928762.0

## We can also sort our dataframe by some column values in either an ascending or descending order

In [189]:
# Sort values in descending order
df.sort_values('runtime', ascending=False)

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit,Capitalized_title,new_profit
index,,,,,,,,,,,,,,,,,,,
1050,31115000,Drama History Romance,ancient rome historical figure cleopatra juliu...,en,Historical epic. The triumphs and tragedy of t...,13.244365,"[{""name"": ""Twentieth Century Fox Film Corporat...",23174,71000000.0,248,The motion picture the world has been waiting ...,Cleopatra,6.7,146,Elizabeth Taylor Richard Burton Rex Harrison R...,Joseph L. Mankiewicz,39885000,CLEOPATRA,39885000.0
136,4000000,Drama Romance War,life and death civil war southern usa loss of ...,en,An American classic in which a manipulative wo...,48.982550,"[{""name"": ""Selznick International Pictures"", ""...",14594,400176459.0,238,The greatest romance of all time!,Gone with the Wind,7.7,970,Vivien Leigh Clark Gable Olivia de Havilland T...,Victor Fleming,396176459,GONE WITH THE WIND,396176459.0
19,30000000,Drama Crime,life and death corruption street gang rape sad...,en,A former Prohibition-era Jewish gangster retur...,49.336397,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...",30728,0.0,229,"Crime, passion and lust for power - Sergio Leo...",Once Upon a Time in America,8.2,1069,Robert De Niro James Woods Elizabeth McGovern ...,Sergio Leone,-30000000,ONCE UPON A TIME IN AMERICA,NaN
104,15000000,Adventure Drama History War,cairo arabian world war i horse jerusalem,en,An epic about British officer T.E. Lawrence's ...,41.286336,"[{""name"": ""Horizon Pictures (II)"", ""id"": 11356}]",22990,69995385.0,216,NaN,Lawrence of Arabia,7.8,851,Peter O'Toole Alec Guinness Anthony Quinn Jack...,David Lean,54995385,LAWRENCE OF ARABIA,54995385.0
20,2000000,Action Drama,japan samurai peasant looting rice,ja,A samurai answers a village's request for prot...,39.756748,"[{""name"": ""Toho Company"", ""id"": 882}]",19840,271841.0,207,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,8.2,878,Toshir\u014d Mifune Takashi Shimura Yoshio Ina...,Akira Kurosawa,-1728159,SEVEN SAMURAI,-1728159.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2381,20000000,Family Animation Adventure,river musical tiger village feral child,en,"Mowgli, missing the jungle and his old friends...",19.819893,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",37659,135680000.0,72,Feel the jungle beat,The Jungle Book 2,5.6,269,John Goodman Haley Joel Osment Mae Whitman Con...,Steve Trenbirth,115680000,THE JUNGLE BOOK 2,115680000.0
1840,20000000,Adventure Fantasy Animation Family,animation,en,The classic tale of 'Peter Pan' continues in D...,15.341196,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",37301,109862682.0,72,The Classic Continues,Return to Never Land,6.1,290,Harriet Owen Blayne Weaver Jeff Bennett Kath S...,Robin Budd,89862682,RETURN TO NEVER LAND,89862682.0
854,858000,Animation Drama Family,forest coming of age best friend loss of loved...,en,Bambi's tale unfolds from season to season as ...,47.651878,"[{""name"": ""Walt Disney Productions"", ""id"": 3166}]",15567,267447150.0,70,A great love story.,Bambi,6.8,1405,Donnie Dunagan Peter Behn Stan Alexander Cammi...,David Hand,266589150,BAMBI,266589150.0
662,12300000,Animation Adventure Family,vulkan loss of mother tyrannosaurus rex earthq...,en,An orphaned brontosaurus named Littlefoot sets...,28.670193,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Uni...",32465,84460846.0,69,A new adventure is born.,The Land Before Time,7.0,640,Gabriel Damon Candace Hutson Judith Barsi Will...,Don Bluth,72160846,THE LAND BEFORE TIME,72160846.0
899,30000000,Animation Family,owl tiger aftercreditsstinger duringcreditssti...,en,"During an ordinary day in Hundred Acre Wood, W...",19.143721,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",40646,14460000.0,63,Oh Pooh.,Winnie the Pooh,6.8,258,Jim Cummings Travis Oates Bud Luckey Craig Fer...,Stephen Anderson,-15540000,WINNIE THE POOH,-15540000.0

In [191]:
# We can also sort by the combination of two columns
df.sort_values(['vote_count','new_profit'], ascending=[False,True]).head()

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit,Capitalized_title,new_profit
index,,,,,,,,,,,,,,,,,,,
22,160000000,Action Thriller Science Fiction Mystery Adventure,loss of lover dream kidnapping sleep subconsci...,en,"Cobb, a skilled thief who commits corporate es...",167.583710,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",40373,8.255328e+08,148,Your mind is the scene of the crime.,Inception,8.1,13752,Leonardo DiCaprio Joseph Gordon-Levitt Ellen P...,Christopher Nolan,665532764,INCEPTION,6.655328e+08
8,185000000,Drama Action Crime Thriller,dc comics crime fighter secret identity scarec...,en,Batman raises the stakes in his war on crime. ...,187.322927,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...",39645,1.004558e+09,152,Why So Serious?,The Dark Knight,8.2,12002,Christian Bale Heath Ledger Aaron Eckhart Mich...,Christopher Nolan,819558444,THE DARK KNIGHT,8.195584e+08
436,237000000,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",40157,2.787965e+09,162,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,2550965087,AVATAR,2.550965e+09
262,220000000,Science Fiction Action Adventure,new york shield marvel comic superhero based o...,en,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",41024,1.519558e+09,143,Some assembly required.,The Avengers,7.4,11776,Robert Downey Jr. Chris Evans Mark Ruffalo Chr...,Joss Whedon,1299557910,THE AVENGERS,1.299558e+09
261,58000000,Action Adventure Comedy,anti hero mercenary marvel comic superhero bas...,en,Deadpool tells the origin story of former Spec...,514.569956,"[{""name"": ""Twentieth Century Fox Film Corporat...",42409,7.831130e+08,108,Witness the beginning of a happy ending,Deadpool,7.4,10995,Ryan Reynolds Morena Baccarin Ed Skrein T.J. M...,Tim Miller,725112979,DEADPOOL,7.251130e+08

# <b>Let us explore some datetime operations and functions

Directive

* #### <b>%a</b>	Weekday as locale’s abbreviated name.	Sun, Mon, …, Sat (en_US)
So, Mo, …, Sa (de_DE)
* #### <b>%A</b>	Weekday as locale’s full name.	Sunday, Monday, …, Saturday (en_US)
Sonntag, Montag, …, Samstag (de_DE)
* #### <b>%w</b>	Weekday as a decimal number, where 0 is Sunday and 6 is Saturday.	0, 1, 2, 3, 4, 5, 6
* #### <b>%d</b>	Day of the month as a zero-padded decimal number.	01, 02, …, 31
* #### <b>%b</b>	Month as locale’s abbreviated name.	Jan, Feb, …, Dec (en_US)
Jan, Feb, …, Dez (de_DE)
* #### <b>%B</b>	Month as locale’s full name.	January, February, …, December (en_US)
Januar, Februar, …, Dezember (de_DE)
* #### <b>%m</b>	Month as a zero-padded decimal number.	01, 02 … 12
* #### <b>%y</b>	Year without century as a zero-padded decimal number.	01, 02, … 99
* #### <b>%Y</b>	Year with century as a decimal number.	0001, 0002, … , 9999
* #### <b>%H</b>	Hour (24-hour clock) as a zero-padded decimal number.	01, 02, … , 23
* #### <b>%I</b>	Hour (12-hour clock) as a zero-padded decimal number.	01, 02, … , 12
* #### <b>%p</b>	Locale’s equivalent of either AM or PM.	AM, PM (en_US)
am, pm (de_DE)
* #### <b>%M</b>	Minute as a zero-padded decimal number.	01, 02, … , 59
* #### <b>%S</b>	Second as a zero-padded decimal number.	01, 02, … , 59
* #### <b>%f</b>	Microsecond as a decimal number, zero-padded on the left.	000000, 000001, …, 999999

In [192]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2888 entries, 0 to 2887
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                2888 non-null   int64
 1   genres                2888 non-null   str
 2   keywords              2845 non-null   str
 3   original_language     2888 non-null   str
 4   overview              2888 non-null   str
 5   popularity            2888 non-null   float64
 6   production_companies  2888 non-null   str
 7   release_date          2888 non-null   int64
 8   revenue               2886 non-null   float64
 9   runtime               2888 non-null   int64
 10  tagline               2730 non-null   str
 11  title                 2888 non-null   str
 12  vote_average          2888 non-null   float64
 13  vote_count            2888 non-null   int64
 14  cast                  2888 non-null   str
 15  director              2888 non-null   str
 16  movie_profit          2888 non-null   int64
 17  Capitalized_title     2888 non-null   str
 18  new_profit            2691 non-null   float64
dtypes: float64(4), int64(5), str(10)
memory usage: 428.8 KB

In [193]:
df['release_date'][0:5]

index
0    34600
1    26372
2    41922
3    36448
4    34615
Name: release_date, dtype: int64

In [203]:
# Importing datetime modules
from datetime import datetime, timedelta
from datetime import date

base_date = datetime(1899, 12, 31)

## <code>strptime</code> means string parser, this will convert a string format to datetime.

## <code>strftime</code> means string formatter, this will format a datetime object to string format.

In [198]:
df['release_date'][0:5]

index
0    34600
1    26372
2    41922
3    36448
4    34615
Name: release_date, dtype: int64

In [225]:
# df['new_release_date'] = pd.to_datetime(df['release_date'].astype(int), unit='D', origin='1899-12-31')

df['new_release_date'] = df['release_date'].apply(
    lambda x: base_date + timedelta(days=int(x))
)

In [222]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2888 entries, 0 to 2887
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                2888 non-null   int64
 1   genres                2888 non-null   str
 2   keywords              2845 non-null   str
 3   original_language     2888 non-null   str
 4   overview              2888 non-null   str
 5   popularity            2888 non-null   float64
 6   production_companies  2888 non-null   str
 7   release_date          2888 non-null   int64
 8   revenue               2886 non-null   float64
 9   runtime               2888 non-null   int64
 10  tagline               2730 non-null   str
 11  title                 2888 non-null   str
 12  vote_average          2888 non-null   float64
 13  vote_count            2888 non-null   int64
 14  cast                  2888 non-null   str
 15  director              2888 non-null   str
 16  movie_profit          2888 non-null   int64
 17  Capitalized_title     2888 non-null   str
 18  new_profit            2691 non-null   float64
 19  new_release_date      2888 non-null   datetime64[s]
dtypes: datetime64[s](1), float64(4), int64(5), str(10)
memory usage: 451.4 KB

In [224]:
df.head()

,budget,genres,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,director,movie_profit,Capitalized_title,new_profit,new_release_date
index,,,,,,,,,,,,,,,,,,,,
0,25000000,Drama Crime,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,NaN,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,Frank Darabont,3341469,THE SHAWSHANK REDEMPTION,NaN,1994-09-24
1,6000000,Drama Crime,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,NaN,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,Francis Ford Coppola,239066411,THE GODFATHER,NaN,1972-03-15
2,3300000,Drama,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000.0,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,Damien Chazelle,9792000,WHIPLASH,9792000.0,2014-10-11
3,63000000,Drama,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753.0,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,David Fincher,37853753,FIGHT CLUB,37853753.0,1999-10-16
4,8000000,Thriller Crime,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762.0,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,Quentin Tarantino,205928762,PULP FICTION,205928762.0,1994-10-09

In [226]:
df['new_release_date'][0]

Timestamp('1994-09-24 00:00:00')

In [227]:
# Month year date
print(df['new_release_date'][0].month)
print(df['new_release_date'][0].year)
print(df['new_release_date'][0].day)
print(df['new_release_date'][0].hour)
print(df['new_release_date'][0].minute)

9
1994
24
0
0

In [230]:
print(date.today())
print(datetime.now())

2026-07-17
2026-07-17 01:05:49.275573

In [ ]:
datetime.now() + 1

In [232]:
# Some operations we can do on datetime
from datetime import timedelta
print(date.today())
print(date.today() - timedelta(days=1))
print(datetime.now() + timedelta(hours=5.5))
print(datetime.now() + timedelta(seconds=60))

2026-07-17
2026-07-16
2026-07-17 06:35:57.062563
2026-07-17 01:06:57.062640

In [233]:
print(df['new_release_date'][0])
print(df['new_release_date'][5])

1994-09-24 00:00:00
2001-07-21 00:00:00

In [234]:
# Difference in two datetime
time_delta=df['new_release_date'][0]-df['new_release_date'][5]
time_delta

Timedelta('-2492 days +00:00:00')

In [235]:
type(time_delta)

pandas.Timedelta

In [236]:
time_delta.total_seconds()

-215308800.0

In [237]:
t1 = pd.to_datetime('1/1/2015 01:00')
t2 = pd.to_datetime('1/1/2015 03:30')

print(pd.Timedelta(t2 - t1).seconds / 3600.0)

2.5

# **Let's explore the unique and missing values**

* ### <code>unique()</code>
* ### <code>nunique()</code>
* ### <code>value_counts()</code>
* ### <code>isnull()</code>
* ### <code>fillna()</code>

In [238]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2888 entries, 0 to 2887
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                2888 non-null   int64
 1   genres                2888 non-null   str
 2   keywords              2845 non-null   str
 3   original_language     2888 non-null   str
 4   overview              2888 non-null   str
 5   popularity            2888 non-null   float64
 6   production_companies  2888 non-null   str
 7   release_date          2888 non-null   int64
 8   revenue               2886 non-null   float64
 9   runtime               2888 non-null   int64
 10  tagline               2730 non-null   str
 11  title                 2888 non-null   str
 12  vote_average          2888 non-null   float64
 13  vote_count            2888 non-null   int64
 14  cast                  2888 non-null   str
 15  director              2888 non-null   str
 16  movie_profit          2888 non-null   int64
 17  Capitalized_title     2888 non-null   str
 18  new_profit            2691 non-null   float64
 19  new_release_date      2888 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(5), str(10)
memory usage: 451.4 KB

In [ ]:
# Find the list of unique values in a column
list(df['original_language'].unique())

['en',
 'ja',
 'it',
 'pt',
 'ko',
 'de',
 'da',
 'fr',
 'es',
 'he',
 'fa',
 'te',
 'id',
 'hi',
 'ro',
 'zh',
 'nl',
 'cn',
 'pl',
 'xx',
 'th',
 'nb',
 'ru',
 'no']

In [243]:
# Counts the number of unique values in a column
df.original_language.nunique()

24

In [244]:
# Give the counts of each category of a variable
df['original_language'].value_counts()

original_language
en    2779
fr      27
es      13
ja      11
de      10
zh       8
it       6
ko       5
cn       5
da       4
pt       3
fa       2
id       2
th       2
ru       2
he       1
te       1
hi       1
ro       1
nl       1
pl       1
xx       1
nb       1
no       1
Name: count, dtype: int64

In [245]:
# Does not make much sense to use value_counts for a numeric variable
df.runtime.value_counts()

runtime
100    91
98     77
106    71
105    68
95     68
       ..
70      1
63      1
248     1
187     1
75      1
Name: count, Length: 127, dtype: int64

In [248]:
# Returns a series of booleans if a column value contains nulls
df2['homepage'].isnull()

0        True
1       False
2       False
3       False
4        True
        ...
2883     True
2884     True
2885    False
2886     True
2887     True
Name: homepage, Length: 2888, dtype: bool

In [249]:
df2[~df2['homepage'].isnull()]

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
5,5,15000000,Fantasy Adventure Animation Family,http://movies.disney.com/spirited-away,129,witch parents kids relationship magic twilight...,ja,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]",37092,274925095,125,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840,Rumi Hiiragi Miyu Irino Mari Natsuki Takashi N...,"[{'name': 'John Lasseter', 'gender': 2, 'depar...",Hayao Miyazaki
7,7,22000000,Drama History War,http://www.schindlerslist.com/,424,factory concentration camp hero holocaust worl...,en,The true story of how businessman Oskar Schind...,104.469351,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",34302,321365567,195,"Whoever saves one life, saves the world entire.",Schindler's List,8.3,4329,Liam Neeson Ben Kingsley Ralph Fiennes Carolin...,"[{'name': 'John Williams', 'gender': 2, 'depar...",Steven Spielberg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,2875,16000000,Thriller Action Science Fiction,http://www.leftbehindmovie.com/,218043,airplane the rapture remake pilot hero,en,A small group of survivors are left behind aft...,33.452469,"[{""name"": ""Stoney Lake Entertainment"", ""id"": 1...",41915,19682924,110,The End Begins,Left Behind,3.7,392,Nicolas Cage Chad Michael Murray Lea Thompson ...,"[{'name': 'Jack Green', 'gender': 2, 'departme...",Vic Armstrong
2876,2876,30000000,Comedy,http://www.meetthespartans.com/,7278,fight queen penguin black hole men,en,From the creators of Scary Movie and Date Movi...,10.608998,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",39471,84646831,84,"The Bigger the Hit, The Harder They Fall",Meet the Spartans,3.7,359,Sean Maguire Carmen Electra Ken Davitian Kevin...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",Jason Friedberg
2880,2880,54000000,Drama,http://www.sonypictures.com/homevideo/catalog/...,8046,new york mentally disabled kidnapping blackmai...,en,Gigli is ordered to kidnap the psychologically...,9.053456,"[{""name"": ""City Light Films"", ""id"": 136}, {""na...",37834,7266209,121,Life doesn't play by the rules.,Gigli,3.5,104,Ben Affleck Jennifer Lopez Justin Bartha Laini...,"[{'name': 'Gary Frutkoff', 'gender': 2, 'depar...",Martin Brest
2881,2881,25000000,Action Adventure Fantasy Horror,http://www.bloodrayne-themovie.com/main/index....,168705,vampire vampire hunter based on video game rom...,en,"In eighteenth century Romania, Rayne, a dhampi...",7.008216,"[{""name"": ""Boll KG"", ""id"": 15127}]",38647,2405420,95,Revenge never tasted so sweet.,BloodRayne,3.5,118,Kristanna Loken Ben Kingsley Michelle Rodrigue...,"[{'name': 'Guinevere Turner', 'gender': 1, 'de...",Uwe Boll
2885,2885,25000000,Action Comedy,http://www.disastermovie.net/,13805,natural disaster violence mortal danger during...,en,"In DISASTER MOVIE, the filmmaking team behind ...",16.238961,"[{""name"": ""Grosvenor Park Media Ltd."", ""id"": 2...",39689,14109284,87,Your favorite movies are going to be destroyed.,Disaster Movie,3.0,240,Matt Lanter Vanessa Lachey Nicole Ari Parker C...,"[{'name': 'Peck Prior', 'gender': 2, 'departme...",Jason Friedberg

In [251]:
# Lets fill the missing values with the value -999
df2['homepage'].fillna('Not Present',inplace = True)

C:\Users\Sandeep Kumar Mishra\AppData\Local\Temp\ipykernel_11820\1301152528.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2['homepage'].fillna('Not Present',inplace = True)

0                                      Not Present
1                     http://www.thegodfather.com/
2                http://sonyclassics.com/whiplash/
3       http://www.foxmovies.com/movies/fight-club
4                                      Not Present
                           ...
2883                                   Not Present
2884                                   Not Present
2885                 http://www.disastermovie.net/
2886                                   Not Present
2887                                   Not Present
Name: homepage, Length: 2888, dtype: str

In [ ]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,release_date,revenue,runtime,tagline,title,vote_average,vote_count,cast,crew,director
0,0,25000000,Drama Crime,NaN,278,prison corruption police brutality prison cell...,en,Framed in the 1940s for the double murder of h...,136.747729,"[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",34600,28341469,142,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,8.5,8205,Tim Robbins Morgan Freeman Bob Gunton Clancy B...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Frank Darabont
1,1,6000000,Drama Crime,http://www.thegodfather.com/,238,italy love at first sight loss of father patri...,en,"Spanning the years 1945 to 1955, a chronicle o...",143.659698,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",26372,245066411,175,An offer you can't refuse.,The Godfather,8.4,5893,Marlon Brando Al Pacino James Caan Richard S. ...,"[{'name': 'Francis Ford Coppola', 'gender': 2,...",Francis Ford Coppola
2,2,3300000,Drama,http://sonyclassics.com/whiplash/,244786,jazz obsession conservatory music teacher new ...,en,"Under the direction of a ruthless instructor, ...",192.528841,"[{""name"": ""Bold Films"", ""id"": 2266}, {""name"": ...",41922,13092000,105,The road to greatness can take you to the edge.,Whiplash,8.3,4254,Miles Teller J.K. Simmons Melissa Benoist Aust...,"[{'name': 'Terri Taylor', 'gender': 1, 'depart...",Damien Chazelle
3,3,63000000,Drama,http://www.foxmovies.com/movies/fight-club,550,support group dual identity nihilism rage and ...,en,A ticking-time-bomb insomniac and a slippery s...,146.757391,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",36448,100853753,139,Mischief. Mayhem. Soap.,Fight Club,8.3,9413,Edward Norton Brad Pitt Meat Loaf Jared Leto H...,"[{'name': 'Arnon Milchan', 'gender': 2, 'depar...",David Fincher
4,4,8000000,Thriller Crime,NaN,680,transporter brothel drug dealer boxer massage,en,"A burger-loving hit man, his philosophical par...",121.463076,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",34615,213928762,154,Just because you are a character doesn't mean ...,Pulp Fiction,8.3,8428,John Travolta Samuel L. Jackson Uma Thurman Br...,"[{'name': 'Quentin Tarantino', 'gender': 2, 'd...",Quentin Tarantino